### ISSUE TITLE
There are some issue on DI layer

### ISSUE THREAD

**Issue by hoangnguyen92dn** [LongJakeparker/SurveysApp#11]
- [x] `RepoModule` - Great to see you are applying DI with Hilt but this layer should be used to provide/bind instance rather than include network logic from here.

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/di/RepoModule.kt#L42-L71

- [x] `ApiServiceHolder` - This class is unnecessary because you are applying Hilt to manage instances. Why do we need to create a holder class to keep the instances for usage?

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/other/ApiServiceHolder.kt#L12-L14

- [x] Keeping `applicationContext` for usage from `SurveysApplication` is violated the dependency injection technique.

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/SurveysApplication.kt#L12-L20

**Comment by LongJakeparker** [comment]
Okay so, I will fix the RepoModule and applicationContext, but the ApiServiceHolder is to prevent loop injection while the refresh token logic needs the Retrofit instance to build the request but the tokenAuthenticator which attached to the OkHttpClient is contains the refresh token logic. 
So to fix the infinite loop, I had to keep the instance or create a definitely difference Retrofit instance. 
It would be great if there is any advice from you.

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker I'd suggest separating different instances for Non-Authorized and Authorized (which requires `Headers`)

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Okay, that's a great approach. I'll fix that

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Regarding `applicationContext`, idydk we can get `applicationContext` from Fragments by using `requireContext().applicationContext` so we don't need to inject instance of Application Context in Fragments

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn yep i forgot that for a moment, thank you for your remind.
