### ISSUE TITLE
Greeting and starting the reviewing process

### ISSUE THREAD

**Issue by hoangnguyen92dn** [LongJakeparker/SurveysApp#6]
Hello Long,

Nice to e-meet you 👋  and thanks for your effort on this submission. My name is Huey - an Android Developer at Nimble and I would like to conduct the feedback via Issue tickets regarding your performance here.

Keep in mind, this is a bidirectional process, so we would love to hear back from you as well, so please don’t hesitate to raise your question/correction in case we missed anything.

If we’re aligned on any issue here and you’d like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and we will follow up on those fixes 😇

I hope you find the process enjoyable. Good luck and happy coding 🤘

**Comment by LongJakeparker** [comment]
Hi @hoangnguyen92dn 👋,

I've finished on fixing all feedbacks (except unit test), it would be great if you have time to take a look at it.

Have a nice day!!

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Thank you. You did well 👍  Have a nice day 🌤️

**Comment by LongJakeparker** [comment]
Hi @hoangnguyen92dn , I updated some unit tests.
Give it a look if you have time and leave your feedback if any.
Thank you. Have a nice day.

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Great 👍  I will take a look asap 👀  Have a nice day ☀️

**Comment by LongJakeparker** [comment]
Hi @hoangnguyen92dn ,

Hope everything is going great, just wanna following up to know if there is any update from you.

Have a nice day 🤟

**Comment by hoangnguyen92dn** [comment]
Hi @LongJakeparker 👋  

I finished my review of your code challenge and the evaluation is being finalized by our team. Ms. Uyên will send you the update via email soon.

Thank you for spending time on the code challenge 👍  

Have a nice day ☀️

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Great!! Thank you for your update.
