### ISSUE TITLE
There are some missing features on requirements

### ISSUE THREAD

**Issue by hoangnguyen92dn** [LongJakeparker/SurveysApp#7]
Following our requirements, you are missing some points as below. If you're having any issue on this or need confirmation please raise it here.

### Application features

- [x] The navigation indicator list (bullets) must be dynamic and based on the API response.

### Technical requirements
- [x] Write unit tests using your framework of choice.

**Comment by LongJakeparker** [comment]
Hi Huey,

About the bullets, i attached it with the ViewPager so it should be dynamic due to the response from the api

And about the unit test, i didn't have enough time to research and write it - not really familiar to me, but i'm going to try to add some basic cases

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Regarding the bullets, we expected to have more bullets when the new items returned from API such as loading more

Ex:
- Page 1: 5 items -> 5 bullets
- Page 2: 5 items -> 10 bullets

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn so the problem is about the loading more feature. Because the bullets are now depend on the data source, so obviously its dynamic. And the loading more feature is basically not in the requirements, hence I would fix that if it is required.

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Since we already define `/surveys` with page number and page size so please add the pagination feature.

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Okay then

**Comment by LongJakeparker** [comment]
Hi @hoangnguyen92dn 👋, is there any requirement for unit test? Because it quite wide, so i don't know the range for it. And how many time left i have for this in review process, i just afraid of making the process become too long.

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Yep. As you can see, UnitTest is a required field in the Technical requirements so it would be better if you could apply it as well. You might have 1-2 days to update for the UnitTest.
