### ISSUE TITLE
There are some issue on UI

### ISSUE THREAD

**Issue by hoangnguyen92dn** [LongJakeparker/SurveysApp#8]
- [x] Should follow design with background on Splash and Login screens
  - There are quite different UI from our design and your submission.

| Submission | Design |
|-|-|
|<img src="https://user-images.githubusercontent.com/6950766/122503829-55fcdd80-d023-11eb-833b-2fdb5881d13c.png" width=250>| <img src="https://user-images.githubusercontent.com/6950766/122503919-73ca4280-d023-11eb-9f70-887d82391454.png" width=250>| 

- [x] As you are defined `values-night` for supporting Dark mode so please update the UI to adapt it correctly

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/res/values-night/themes.xml#L3-L15

- [x] `DataBinding` should be applied on `SurveySlidePagerAdapter` to get rid of `binding.ivCoverImage.load`

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/view/adapter/SurveySlidePagerAdapter.kt#L30-L34

**Comment by LongJakeparker** [comment]
Actually, i tried to follow the design at first, but i couldn't find the materials to build that UI (logo, background image), so i thought its okay to change a little bit. 

Well, i will fix that, thanks with that 🤟

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Heyy, about the design, where could I find those materials? (the logo and background image)

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker You can get the resources once logged in and switched to the Editor mode.

![image](https://user-images.githubusercontent.com/6950766/122509234-9f522a80-d02d-11eb-95dd-28812705b906.png)

**Comment by sleepylee** [comment]
@hoangnguyen92dn editor mode might not be available publicly. Let me ask the designer to see if we can tweak these settings

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Please sign up and log in with your personal account. Then you can export the resources for usage and styles (font size, color, ...)

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Okay i got it now, thank you then.

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn so about the `supporting Dark mode`, I am still not get what you want me to do while there is only have one design, should I remove it or make it the same with current theme?

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker If you switch your Android device to Dark mode, you would see the TextViews, Images... are not in the high contrast. You can remove it if you don't suppose to support Dark mode.
