### ISSUE TITLE
There are some issue on Network layer

### ISSUE THREAD

**Issue by hoangnguyen92dn** [LongJakeparker/SurveysApp#9]
- [x] Duplicated mapping success and error handling on `AuthRepository`

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/repository/AuthRepository.kt#L24-L32

-----

- [x] `BaseException` with the list of `errors` but you are always getting the first item.

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/repository/AuthRepository.kt#L28-L32

-----

- [x] Using inconsistency param annotations for API request: `@FormUrlEncoded` with `@Field` and `@Body`. Use `@Body` to send objects in request with `HashMap<String, Any>` is not a good approach.

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/api/ApiService.kt#L45-L48

-----

- [x] `Authorization` is attached to the header on every request with an empty value

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/di/RepoModule.kt#L47-L51

```
    2021-06-18 08:53:34.804 8297-9827/com.example.surveysapp D/OkHttp: --> POST https://survey-api.nimblehq.co/api/v1/oauth/token
    2021-06-18 08:53:34.804 8297-9827/com.example.surveysapp D/OkHttp: Content-Type: application/x-www-form-urlencoded
    2021-06-18 08:53:34.804 8297-9827/com.example.surveysapp D/OkHttp: Content-Length: 173
    2021-06-18 08:53:34.804 8297-9827/com.example.surveysapp D/OkHttp: Authorization: 
    2021-06-18 08:53:34.804 8297-9827/com.example.surveysapp D/OkHttp: email=dev%40ninblehq.co&password=12345678&grant_type=password&client_id=6GbE8dhoz519l2N_F99StqoOs6Tcmm1rXgda4q__rIw&client_secret=_ayfIm7BeUAhx2W1OUqi20fwO3uNxfo1QstyKlFCgHw
    2021-06-18 08:53:34.804 8297-9827/com.example.surveysapp D/OkHttp: --> END POST (173-byte body)
```

-----

- [x] Checking `expireTime` in local is unnecessary because it would be expired anytime due to the delay until the request sent to the server. And we also implemented the refresh token mechanism so we could skip the validating logic.

https://github.com/LongJakeparker/SurveysApp/blob/4f4ee4b2b4e46488eeb83055751f92d1a84ebeb7/app/src/main/java/com/example/surveysapp/di/RepoModule.kt#L92-L120

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn I got confused with the `errors` actually, so I have to display all errors in the list at the same time, haven't I?

I think check the `expireTime` before send the request is also necessary to reduce the unnecessary requests while those are obviously expired (ex: expired at yesterday already) so we can get the refresh token directly.

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker You can ignore my comment about the `errors` 🙏  The `list` is needed because API will return the list of errors but displaying the first error would be fine.

> I think check the expireTime before send the request is also necessary to reduce the unnecessary requests while those are obviously expired (ex: expired at yesterday already) so we can get the refresh token directly.

Yeah. It would be the case. But on another side, the app has to check the expire on every API request. And the token is valid on local but it's revoked on the API side :man_shrugging:

**Comment by LongJakeparker** [comment]
Well, i simply thinks that we should avoids to send unnecessary requests to reduce server-side work, and the case you listed is rarely happened. Moreover, i also thinks the comparison in the app cannot compares with the request number. So i still think we should keep it there 🤔

**Comment by LongJakeparker** [comment]
hi @hoangnguyen92dn , please correct me if I am wrong, I am very willing to hear your feedback.

**Comment by hoangnguyen92dn** [comment]
> So i still think we should keep it there

@LongJakeparker Yup. It's optional due to in the real-life scenario, we have to trade-off between performance and user cellular data. You can leave it there.

**Comment by LongJakeparker** [comment]
> Using inconsistency param annotations for API request: @FormUrlEncoded with @Field and @Body. Use @Body to send objects in request with HashMap<String, Any> is not a good approach.

Hi @hoangnguyen92dn , I'm still not really clear with the comment above, can you give me more details about it? What problem with the @Body and HashMap<String, Any>?

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Retrofit supports send objects in Request Body, that's means you should create a class to wrap the params for the API request. `HashMap<String, Any>` is really old fashion and we should not do that.

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Ah okay, I got you this point now. So how about the inconsistency of parameter annotations? means I should only use @FormUrlEncoded with @field or @Body, not both?

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker Yep. Reviewers would be confused by the same `@POST` method but you are handling it in different ways. Consistency is one of the top indicators of good code 👨‍💻

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Okay I understand the importance of consistency, but the problem is the API `forgotPassword` is required with json format (ex: ` "user": {
        "email": "junan.cs@gmail.com"
    })` which would return error if it is encoded. So I can not use @Field, right?
    In the other hands, create a wrapper class is quite inflexible, while sometimes we only need  one or two Fields, so in this case @Field is more suitable. 
    So how can I keep the consistency for those cases 🤔 Couldn't we flexible for this?

**Comment by hoangnguyen92dn** [comment]
@LongJakeparker The classes with 1 or 2 fields are still fine. If you have 5 endpoints, let's create 5 classes for request. For ex: LoginRequest, ForgotPasswordRequest, GetSurveyRequest... And it's also easier for enhance, if the endponts require new params for request body we will just need to update Request classes instead of ApiService class.

**Comment by LongJakeparker** [comment]
@hoangnguyen92dn Okay you make it clear now. Your insights are valuable. Thank you
